name: CI/CD Pipeline
on:
  push:
    branches: [ master ]
env:
  REGISTRY: ghcr.io

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Tests
        run: mvn -B test
        
  build:
    needs: tests
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml
      - run: mkdir staging && cp target/*.jar staging
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: RunnableJar
          path: staging

  push-image-ghcr:
    needs: build
    name: Deploy Images to ghcr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY}}
          username: ${{ github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
          logout: true

      - name: Build the Docker Image
        run: |
          docker build . --tag "ghcr.io/${{github.actor}}/devops-demo:latest"
          docker push ghcr.io/${{github.actor}}/devops-demo:latest