name: CI Pipeline (DOC1)

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: My First Pipeline in DOCS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo "Continuous Integration"